name: scouting_app
description: A Flutter app for scouting with a tab bar.

version: 1.0.0

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_inappwebview: ^5.3.2
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  http: ^1.2.2
  shared_preferences: ^2.0.15
  flutter_colorpicker: ^1.0.3
  flutter_form_builder: ^9.3.0
  image: ^3.0.1
  pretty_qr_code: ^3.3.0
  flutter_cache_manager: ^3.4.0
  flutter_bloc: ^8.1.6
  dio: ^5.5.0+1
  syncfusion_flutter_datagrid: ^26.2.9
  flat: ^0.5.0
  syncfusion_flutter_charts: ^26.2.14
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_drawing_board: ^0.9.5
  scribble: ^0.10.0+1
  path_provider: ^2.1.5
  number_paginator: ^0.4.1
  flutter_dotenv: ^5.2.1


dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.0
  lint: ^1.8.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/PolarBearHead.png
    - assets/2024GameField.png
    - assets/2024BlankAutoField.png
    - assets/Note.png
    - assets/AutosGameField.png
